#:kivy 1.0

<Tasks>:
    BoxLayout:
        id:box
        orientation:
            'vertical'
        size_hint_y:
            None
        height:
            self.minimum_height


<Tarefa>:
    size_hint_y:
        None
    Label:
        id:label
        font_size:
            30
    Button:
        text:
            'X'
        size_hint_x:
            None
        width:
            60
        on_release:
            app.root.ids.box.remove_widget(self.parent)

