#:kivy 1.0

<Gerenciador>:
    Screen:
        Button:
            text:
                'Ver tarefas'
            on_release:
                root.current = 'task_list'
    TaskList:
        name:
            'task_list'

<TaskList>:
    BoxLayout:
        orientation:
            'vertical'
        ScrollView:
            BoxLayout:
                id:box
                orientation:
                    'vertical'
                size_hint_y:
                    None
                height:
                    self.minimum_height
        BoxLayout:
            size_hint_y:
                None
            height:
                60
            TextInput:
                id:texto
            Button:
                text:
                    '+'
                size_hint_x:
                    None
                width:
                    60
                on_release:
                    root.addWidget()

<Tarefa>:
    size_hint_y:
        None
    Label:
        id:label
        font_size:
            30
    Button:
        text:
            'X'
        size_hint_x:
            None
        width:
            60
        on_release:
            app.root.get_screen('task_list').ids.box.remove_widget(self.parent)

